-- ============================================================
-- KnockIQ — Manager-set temporary password + phone field
--
-- Adds two pieces of state to public.users so a manager can finish
-- onboarding a rep WITHOUT requiring a working transactional-email
-- provider (Resend). The "send a magic invite link" flow remains
-- the default; this migration just unblocks the alternative path:
--
--   1. Manager sets a temporary password in the Add Rep form.
--   2. manage-team edge function creates the auth user via
--      auth.admin.createUser({ email, password, email_confirm: true })
--      and stamps `force_password_change = true` on public.users.
--   3. Manager texts the credentials to the rep (using the new
--      `phone` column to deep-link an SMS draft).
--   4. On first login, the app's auth gate sees force_password_change
--      and routes the rep to /set-password before anything else.
--   5. SetPassword.jsx clears the flag after the rep picks a real one.
--
-- Idempotent (`IF NOT EXISTS`, `IF EXISTS`) so it's safe to re-apply.
-- ============================================================

-- ── 1. Make `phone` a real, optional contact field ──────────────────────────
-- The original schema had `phone TEXT UNIQUE NOT NULL` from the
-- pre-email-auth era — the handle_new_user trigger papered over it
-- by stuffing the email value into it. That meant the column was
-- never trustworthy as "the rep's phone number." Drop both
-- constraints so we can store a real (possibly NULL) phone number.
ALTER TABLE public.users
  ALTER COLUMN phone DROP NOT NULL;

DO $$
DECLARE
  cname text;
BEGIN
  -- The unique constraint name is autogenerated; look it up by column.
  SELECT con.conname INTO cname
  FROM pg_constraint con
  JOIN pg_attribute  att ON att.attrelid = con.conrelid AND att.attnum = ANY(con.conkey)
  WHERE con.conrelid = 'public.users'::regclass
    AND con.contype  = 'u'
    AND att.attname  = 'phone'
  LIMIT 1;
  IF cname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.users DROP CONSTRAINT %I', cname);
  END IF;
END $$;

-- ── 2. Track whether the next login must reset the password ─────────────────
-- Set to TRUE when a manager creates a rep with a temporary password.
-- Cleared by SetPassword.jsx once the rep picks their own.
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS force_password_change boolean NOT NULL DEFAULT false;

-- ── 3. Stop the new-user trigger from polluting `phone` with email ──────────
-- The original trigger inserted `coalesce(NEW.phone, NEW.email, '')`
-- into the phone column. Now that `phone` is a real contact field,
-- leave it NULL on signup — it gets filled in by the manage-team
-- edge function (when adding a rep) or by the rep on their profile.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.users (id, full_name)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', '')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- Note: existing RLS policy "Users can update own profile" already
-- permits a rep to clear their own `force_password_change` flag, so
-- no policy changes are needed for the SetPassword.jsx flow.
